### ISSUE TITLE
TFCompat and Firmalife mallet texture issue

### ISSUE THREAD

**Issue by Tavarnarmo** [Mrthomas20121-Mods/TFCompat#10]
Hello! When I enable TFCompat textures of mallets from Firmalife dissapear. Could you check it? :) Tested on world with only TFCompat and Firmalife as mods, latest version of everything.

**Comment by Mrthomas20121** [comment]
already known.

**Comment by AdiLovee** [comment]
i know it says fixed in dev but the new beta still is broken with it.
