### ISSUE TITLE
Request: Config option to disable certain modules

### ISSUE THREAD

**Issue by SeriousCreeper** [Mrthomas20121-Mods/TFCompat#3]
Heya!

Was wondering if we could get a config option to disable certain modules? For example i'm using BWM, Pyrotech, and Rustic. I would like to keep the BWM and Rustic changes you made, but not the pyrotech ones (cause i changed how the progression for it works in general). 

Would be awesome if that'd be possible :D 

Cheers,
SC

**Comment by SeriousCreeper** [comment]
Actually to add to that - being able to decide what kind of changes are being applied per mod would even be better (seeing as you are adding pyrotech oven recipes, i wouldn't mind those, but disable the anvil ones and such). 
Wouldn't mind making a pull request with those config changes if you don't mind!

**Comment by Mrthomas20121** [comment]
consider it done.

**Comment by SeriousCreeper** [comment]
you da best :D thanks!
