### ISSUE TITLE
Error Message between TFC and Pyrotech

### ISSUE THREAD

**Issue by Xelbayria** [Mrthomas20121-Mods/TFCompat#4]
The message error are: 
[PARSE] Unable to find registered block: tfc:plants/scutchgrass:2342
[PARSE] Unable to find registered block: tfc:plants/scutchgrass:xxxx

=========================================================

How to recreate the problem. You'll need 
-TerraFirmaCraft-MC1.12.2-1.7.6.164
-pyrotech-1.12.2-1.4.34
-dropt-1.12.2-1.18.0
-athenaeum-1.12.2-1.19.2
-tfccompat-1.1.4

Forge Version: forge-14.23.5.2854

=========================================================
Once you've them, you don't need to worry about the script folder and just leave it empty. Run the game and go into the single world. use the command: 
/dropt reload

it will run the script files and provide a message if there are any problems. I got 2 message errors from 2 files. Let me know if you are able to re-create this problem and have the same result. OR is it just me.

**Comment by Mrthomas20121** [comment]
not related to TFCompat.
