### ISSUE TITLE
More complete description of mod

### ISSUE THREAD

**Issue by yodaldevoid** [Mrthomas20121-Mods/TFCompat#6]
I can't find a thorough description of what this mod actually does to add compatibility.

For example, I want to know how it adds compatibility for Thaumcraft. Does it add ore-gen for the Thaumcraft ores (quicksilver, amber, etc.)? Does it fix any Thaumcraft recipes? The same goes for all of the other mods.

**Comment by Mrthomas20121** [comment]
the thaumcraft module just add Thaumium and void metal as tfc metal. i changed the way to obtain quicksilver. the rest is unchanged. There will be more stuff added once i'm done with my university exams
