### ISSUE TITLE
Suggestion for PR (Chisel + Chisel & Bits)

### ISSUE THREAD

**Issue by Lumintorious** [Mrthomas20121-Mods/TFCompat#7]
Would it be ok if I made a PR that added Chisel and Chisel & Bits compat?

I want to make tools that are more consistent with the TFC metals and that are different than having 3 kinds of chisels in the game (breaks immersion a little).

* The Chisel compat would be adding a Carver's Nail (Long, pointy kind of chisel without handle, requires hammer in offhand) from all of the TFC tool metals with bronze = normal chisel functionality, iron/steel = diamond chisel functionality, high end stuff = iChisel functionality

* The Chisel & Bits compat would be adding bit Hacksaws from all of the TFC tool metals that would scale in durability and act like the bit chisels.

If this addon is not about adding tools, I can make an additional addon.

**Comment by Mrthomas20121** [comment]
it's up to you. i don't mind if it's in TFCompat or not. just note that you might not be able to test your feature in dev.
for my part, i don't test TFCompat in dev, i have a dedicated curseforge instance for it.

**Comment by Lumintorious** [comment]
I fixed it, you can use Not Enough IDS and it will work in dev :)

**Comment by Mrthomas20121** [comment]
that's not the thing that concerned me lol
