### ISSUE TITLE
Crash with TFCompat and Mods.

### ISSUE THREAD

**Issue by Mrthomas20121** [Mrthomas20121-Mods/TFCompat#9]
TFC Tech did some change which removed wood dust. since some recipes use it, it crash.

**Comment by jklw10** [comment]
any estimates on how long this will take to fix and is there a workaround other than removing tfc or mekanism?

**Comment by jklw10** [comment]
downgrading tfc_edit
 to earlier version seemed to work

**Comment by Mrthomas20121** [comment]
> 
> 
> any estimates on how long this will take to fix and is there a workaround other than removing tfc or mekanism?

already fixed. i just didn't have time to push a fix to curseforge.

**Comment by SlayDigger** [comment]
will this fix be pushed to curseforge soon?
